datasource:
  url: jdbc:h2:tcp://localhost/~/test # db url
  driver-class-name: org.h2.Driver # db driver ???? url ??? ?? ???? ???
  username: hong
  password:
  schema: schema.sql # ddl file
  initialization-mode: always

mybatis:
  mapper-location: mapper/**/*.xml # Mybatis mapper.xml ?? ??
  type-aliases-package: org.example.demo.rest.domain #mapper?? resultType ????
  configuration:
    map-underscore-to-camel-case: true

logging:
  file:
    name: ${user.dir}/log/test.log  # ?? ?? ????.
  level:  # ? package ?? ?? ??? ??? ? ??.
    com.project.study : error
    com.project.study.controller : debug

server:
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8